name: Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets: [{ os: windows-latest, type: windows }]
    name: Gyroflow for ${{ matrix.targets.type }}
    runs-on: ${{ matrix.targets.os }}
    env:
      BUILD_APP_STORE_BUNDLE: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
      IS_MANUAL_DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}
      FORCE_ARCH: x86_64
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.targets.type }}-gyroflow-0
      - name: Dependencies cache
        id: extcache
        uses: actions/cache@v4
        with:
          path: '${{ github.workspace }}/ext/'
          key: ${{ matrix.targets.type }}-gyroflow-ext-0

      - name: Prepare Vulkan SDK
        uses: johnnynunez/setup-vulkan-sdk@v1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers
          vulkan-use-cache: true

      - name: Force qml-video-rs rebuild (Win)
        run: |
          rm -r -force ${{ github.workspace }}/target/deploy/build/qml-video-rs* -ErrorAction SilentlyContinue
          rm -r -force ${{ github.workspace }}/target/x86_64-pc-windows-msvc/deploy/build/qml-video-rs* -ErrorAction SilentlyContinue
          rm -r -force ${{ github.workspace }}/target/release/build/qml-video-rs* -ErrorAction SilentlyContinue

      - name: Save Windows signing key
        run: |
          echo "${{ secrets.MS_STORE_SIGNING_KEY }}" > ${{ github.workspace }}/_deployment/windows/msix_signing_key.pfx.b64
          certutil -decode ${{ github.workspace }}/_deployment/windows/msix_signing_key.pfx.b64 ${{ github.workspace }}/_deployment/windows/msix_signing_key.pfx

      - uses: extractions/setup-just@v2

      - name: Build Gyroflow (Windows)
        env:
          MS_STORE_SIGNING_PASS: ${{ secrets.MS_STORE_SIGNING_PASS }}
        run: |
          just install-deps
          just deploy
          if ("$Env:BUILD_APP_STORE_BUNDLE" -eq "true") { just bundle }

      - name: Save debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: Gyroflow-debug-symbols-${{ matrix.targets.type }}
          path: |
            ${{ github.workspace }}/target/x86_64-pc-windows-msvc/deploy/deps/gyroflow.pdb
            ${{ github.workspace }}/target/x86_64-pc-windows-msvc/deploy/*.pdb
      - name: Save Binaries
        uses: actions/upload-artifact@v4
        with:
          name: Gyroflow-${{ matrix.targets.type }}
          path: _deployment/_binaries/*.*

  github_release:
    name: Create GitHub release
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - run: Get-ChildItem -Recurse -File

      - if: startsWith(github.ref, 'refs/tags/')
        run: rm -rf ./Gyroflow-debug-symbols*

      - name: Publish
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            ./Gyroflow-windows/Gyroflow-windows64.zip
  winget_release:
    name: Publish to WinGet
    needs: github_release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    # If this fails, go to gyroflow/winget-pkgs on GitHub and sync fork
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: Gyroflow.Gyroflow
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: 'Gyroflow\-windows64\.zip$'